### ISSUE TITLE
Server is not accessing db in current setup

### ISSUE THREAD

**Issue by hintron** [Victory-Game-Studios/Oldentide#20]
In SQLConnector.cpp, it accesses the db in line 13 like this:

`    sqls = sqlite3_open("db/Oldentide.db", &database);
`

However, when the make file creates the binary, it is placed in the Server/bin/ directory. So the above line actually tries to go to Server/bin/db/, when it really is Server/db/. This is because the sqlite3_open() command is relative to the binary file, not the source file (I think).

I suggest changing the makefile so that it creates the db in Server/bin/db instead of Server/db

**Comment by Jldevictoria** [comment]
I usually run the Server from the base "Server" directory by running bin/Server <port>
