### ISSUE TITLE
Rename Object class

### ISSUE THREAD

**Issue by ajgoda90** [Victory-Game-Studios/Oldentide#24]
Object is a programming term so it may be confusing to those reading the code. GameObject or some other name would be better.

**Comment by Jldevictoria** [comment]
Yeah I thought about this.

I feel like GameObject might already be used by Unreal... so I wonder if there is another name like GObject or GenObject or something...

**Comment by ajgoda90** [comment]
What is the general idea of the class? Would Item work? Theres also nothing wrong with making the name longer like InGameObject or OldentideObject(though that's a little obscure).
