### ISSUE TITLE
Delete Artifacts folder

### ISSUE THREAD

**Issue by ajgoda90** [Victory-Game-Studios/Oldentide#25]
No need to keep around old code with version control.

**Comment by hintron** [comment]
I think if there is a need to mark old code as good, we should consider tagging it in Git. I'm going to do that so I can mark a working state of my PasswordGenerator before I change it up a lot,

**Comment by Jldevictoria** [comment]
I've been hanging onto the Artifacts folder because I use to to go back and look at my old code a lot, but I think it is about at the point where we could let it rest in the old commits...  I'll delete it today.
