### ISSUE TITLE
Better defined separation between GameState and OldentideServer

### ISSUE THREAD

**Issue by hintron** [Victory-Game-Studios/Oldentide#26]
I think OldentideServer.cpp should be the only file that has to deal with packets. I think that GameState.cpp shouldn't have to know about packets, and that the functions should be passed values, not packets. That way, the separation of logic will be more clear, with the one file worrying about packet/ip stuff and connecting things, and the other file worrying about actual game logic. @Jldevictoria What do you think?

**Comment by Jldevictoria** [comment]
Sounds like a good idea, but will probably take quite a bit of code restructuring.

**Comment by hintron** [comment]
I don't think it will be too bad, especially if we start now

**Comment by Jldevictoria** [comment]
This should be fixed, I'm going to test it out when I get home to make sure it compiles and works.
