### ISSUE TITLE
Online Book/Documentation Suggestion

### ISSUE THREAD

**Issue by hintron** [Victory-Game-Studios/Oldentide#29]
I think it would be cool to eventually host an online book for Oldentide, using something like [Gitbook](https://github.com/GitbookIO/gitbook). It could have sections for installation, server management, client usage, game mechanics, lore and backstory, stats/items/spells/etc, locations/maps, code documentation, and other documentation. It could be hosted at www.oldentide.com.

Here is an example site: http://docs.duckduckhack.com/
Here is an example of a site that uses something else similar to gitbook: http://intermezzos.github.io/book/

**Comment by Jldevictoria** [comment]
Github has an integrated Wiki that I have been using.

**Comment by Jldevictoria** [comment]
I think the Github Wiki is plenty for now.
