### ISSUE TITLE
Create a system to initialize the GameState with NPCs and GameObjects from DB.

### ISSUE THREAD

**Issue by Jldevictoria** [Victory-Game-Studios/Oldentide#30]
One of the main functions of the GameState is to maintain an active list of all:

**Players**,
**NPCs**, and
**GameObjects**. 

that exist in the game in real time.

Players are actual logged in human clients.  Players have a names, professions, levels, skills, location etc... It is imperative that we add to the existing Player class to give the Server a way of tracking connection information (I'm thinking we will just add a sockaddr struct to the player class and populate it with the player as he logs in.)

NPCs are Non-Player Characters are a much simpler version of a Player because they do not need player information or anything.  Each NPC object in the gamestate will eventually represent a NPC/Creature/Boss etc... in the game.  The most important characteristics of a NPC are its name, health, location and perhaps some way of tracking their skills/dmg.  

GameObjects are any non-living object in the game.  I think it is a good way to add objects in the environment such as a chest or bag.  It could/should probably be extended to include things like doors, traps, levers etc...

This issue really contains two main objectives: 

**Create an intantiateWorld (Or something like that) method in the GameState class that pulls all the NPC and GameObject data from the database on server startup.  This is basically populating the memory of the bare restarted server.**

**Create some way to populate the database with NPCs and GameObjects.  I think a good way to do this is to have some sort of interface where you can add and remove NPCs from the game by adding them to an XML file and running a server command to fill the NPC table with records based on what was read in the file.**

The Player, Character, NPC and GameObject classes may need to be reworked to support the way we want them to be implemented.  I will start looking into how to populate the server, but @ajgoda90 mentioned that he had some interesting ideas about how to improve these classes, so I want to add him in on this issue if he wants to help.

**Comment by Jldevictoria** [comment]
I reworked the Player, Npc, and Character classes and deleted the GameObject class to improve Player/Npc handling.  Going to look at initialization next.

**Comment by Jldevictoria** [comment]
Note to self: remove maxHp, maxBp etc... these are calculated by using constitution and intelligence anyways, so you had the correct implementation already.

**Comment by Jldevictoria** [comment]
Note to self: https://www.sqlite.org/cli.html#csv

**Comment by jr00t2** [comment]
Another possibility would be to just use Json format ... They are pretty readable and easier to im-/export... You could even save the whole game information in a database field and reload + populate all of them on Server startup. Just an idea

**Comment by Jldevictoria** [comment]
Check out https://github.com/Victory-Game-Studios/Oldentide/blob/master/Server/db/Backup.sh and https://github.com/Victory-Game-Studios/Oldentide/blob/master/Server/db/Restore.sh  I think this is a pretty simple way to do it with sqlite3, because they have built in csv backup functions.

**Comment by Jldevictoria** [comment]
I think this is basically done...  Just need to fully populate the npcs.init script. https://github.com/Victory-Game-Studios/Oldentide/blob/master/Server/db/npcs.init

**Comment by Jldevictoria** [comment]
updated. see commit #330.
