### ISSUE TITLE
Specify Exact Version of Unity

### ISSUE THREAD

**Issue by hintron** [Victory-Game-Studios/Oldentide#34]
Unity will complain when opening up the project unless the exact version is installed. So I propose that Unity 5.4.2 is specified in the top-level README. Even when I tried using Unity 5.4.5 (same major and minor number, but different patch number), it complained.

After downloading 5.4.2, it worked without complaint. Specific versions of Unity can be downloaded here: [https://unity3d.com/get-unity/download/archive](https://unity3d.com/get-unity/download/archive)

**Comment by Jldevictoria** [comment]
The version is in the README.md, but it looks like I haven't updated it recently

It still says 5.4

I'll change it to show 5.4.2
