### ISSUE TITLE
Make Oldentide Game Webserver HTTPS

### ISSUE THREAD

**Issue by hintron** [Victory-Game-Studios/Oldentide#35]
We should get the Oldentide game webserver up and running with HTTPS (make it optional/flag-based, so people can get it up with HTTP first).

I've already created an HTTPS node/express-based website and documented all the steps with [let's encrypt](https://letsencrypt.org/), so this is something I can easily do. I can also document it for Oldentide users.

HTTPS is critical if we want any level of security.

**Comment by Jldevictoria** [comment]
Go for it, you can make a subfolder in ~/Website/ and make sure you put all the documentation in a README.md file.  Also update the website README.md as well.

**Comment by Jldevictoria** [comment]
Done!
