### ISSUE TITLE
Use <cstdint> data types for all C/C++ code

### ISSUE THREAD

**Issue by hintron** [Victory-Game-Studios/Oldentide#37]
I think it could be good to convert all data types to cstdint types for clarity. For example, chars, ints, etc. could be labeled uint8_t, int32_t, etc. This will make it perfectly clear how many bits and bytes each type takes.

I think it will help reduce the burden of remembering the designations between a short, int, long int, and long long int for various machines.

**Comment by Jldevictoria** [comment]
Michael you might be able to answer this better, but does messagepack overwrite the need for this?

**Comment by hintron** [comment]
I think messagepack helps, but I also think using the cstdints is a good idea.

**Comment by Jldevictoria** [comment]
Dropping C++.
