### ISSUE TITLE
Don't let Server Makefile nuke the db by default

### ISSUE THREAD

**Issue by hintron** [Victory-Game-Studios/Oldentide#38]
I think the InitializeDB.sql script should not be executed on `make`. Maybe `make db` would be better, or put in some logic that checks to see if there are accounts in the db and ask for permission before dropping all tables.

I just don't want this to bite us later. I'm already sad that I have to create a new test account :'(

**Comment by Jldevictoria** [comment]
I'm getting rid of the makefile with this go solution.
We will need to initialize the database from the sqlite commandline or integrate it into our Go program somehow.

I'll be redoing the db folder soon.
