### ISSUE TITLE
Transition to Unity 5.6.0p1

### ISSUE THREAD

**Issue by Jldevictoria** [Victory-Game-Studios/Oldentide#39]
I think it is time we update Unity.  We are a few versions behind, and I think that it is beneficial to update now.

https://unity3d.com/unity/qa/patch-releases/5.6.0p1

There is an API updater that should fix game asset errors from previous version.

https://docs.unity3d.com/Manual/APIUpdater.html

I will push an updated change once it works!

**Comment by hintron** [comment]
Will it be mostly the same, or are there​ a lot of new features?

**Comment by Jldevictoria** [comment]
There are quite a few updates.  Most of them should have little or no update on our project so far.  You can look at all the changelogs to see them:

https://unity3d.com/unity/qa/patch-releases

I think it is smart to keep updating regularly though, because occasionally they implement tools that could help us.

**Comment by Jldevictoria** [comment]
Okay the commit I just made should be ready for 5.6.0p1

https://github.com/Victory-Game-Studios/Oldentide/commit/4449a152c1c17dc32a77aa9a8834f9032810ee55
