### ISSUE TITLE
Validate username and email registration inputs

### ISSUE THREAD

**Issue by ajgoda90** [Victory-Game-Studios/Oldentide#40]
Currently there is no server side username or email validation. This means one can successfully register with an invalid email. Also this is vulnerable to script injection if we show usernames/emails anywhere.

**Comment by hintron** [comment]
Are you talking about sanitizing the input values themselves in the webpage form, or validating that an email belongs to someone?

**Comment by ajgoda90** [comment]
The input values from the form. They need to be validated on the server because it's very easy to bypass client side validation. We're not currently checking that it's even an email address.
