### ISSUE TITLE
Rename "key" column in accounts table to "hash"

### ISSUE THREAD

**Issue by ajgoda90** [Victory-Game-Studios/Oldentide#43]
The value we're storing is a hash/salt combo output by bcrypt. The term "key" is sort of accurate, but it also has other meanings in SQL. We should also change any places that refer to it as a key in comments or function/variable names.

**Comment by hintron** [comment]
Why not passphrase or passkey? Hash is also an overloaded term.
I agree that it's not a password, so we don't want to name it that.

**Comment by Jldevictoria** [comment]
Updated to hash in b26f69d2a02a40e4bf9e91da08f2fe883ddd6922
