### ISSUE TITLE
Make Server Thread-safe

### ISSUE THREAD

**Issue by hintron** [Victory-Game-Studios/Oldentide#45]
Now that we have a thread pool and multiple threads, we need to make sure that all global variables used between threads are properly wrapped with a semaphore (I'm looking at you, GameState.cpp... players, sessions, etc.).

There are other things that may need protection as well. ~~Do the socket-related things need to be wrapped with semaphores?~~ The sqlite db (maybe not because of atomic operations)? We need to identify what are the global variables shared between threads, and what is on each thread's stack.

If we don't do this, then we'll most likely end up with random crashes in the server as the load increases that wouldn't show up in simple test cases.

When a thread is created, anything NOT on the stack is shared, right? What about objects? I'm having a hard time wrapping my head around what is being shared and what isn't. Are all objects created with `new` shared between threads, and all other objects (strings, etc.) not?

**Comment by hintron** [comment]
Update - socket-related things are thread safe. See [](http://stackoverflow.com/questions/1981372/are-parallel-calls-to-send-recv-on-the-same-socket-valid)

**Comment by ajgoda90** [comment]
To answer about semaphores on database operations, even if they are atomic, if we're ever doing anything based on some sort of global state(a database value that can be accessed from multiple threads for instance) then we'd want a semaphore so that the state can't change between checking it and doing what we're going to do based on it.

**Comment by hintron** [comment]
I believe that all global variables accessed in the server's worker threads are now properly protected with mutexes.

To protect the db, I simply wrapped all of Server's gameState accesses with a mutex, essentially making all gameState code atomic (according to the worker threads, at least).

I'll close this temporarily for now, and reopen it if any issues crop up.
