### ISSUE TITLE
Login System Defined

### ISSUE THREAD

**Issue by Jldevictoria** [Victory-Game-Studios/Oldentide#5]
Create a model of how the login system for the game will work.  This should include graphics, theory, back-end design, and front-end design.

**Comment by hintron** [comment]
Ok, looks like this needs to be updated a bit. I guess the main idea is that the login system should be through a web page on a web-server called "goblin." This web server will be hosted right next to the actual game server, and will have access to the same databases.

We are considering creating the web server using nodejs and expressjs, using the bcrypt node module to save and store passwords (replacing the current implementation), and using a node module to tap into the sqlite dbs.

@Jldevictoria Does this sound about right? Anything to add/change/explain?

**Comment by hintron** [comment]
Is this defined accurately? Do we need to specify the separation of duties between the webserver and the server better?

**Comment by Jldevictoria** [comment]
Login will be done through the Web server using regular https POST.

I just added the script to the Login_Screen Scene in Unity to post to the given login screen.

It needs to be improved to scrape the session ID from the headers and store it in Unity.

See [LoginManager.cs](https://github.com/Victory-Game-Studios/Oldentide/blob/master/Assets/Network/LoginManager.cs)
