### ISSUE TITLE
Investigate Package Manager

### ISSUE THREAD

**Issue by hintron** [Victory-Game-Studios/Oldentide#56]
Right now, we are essentially doing custom package management in the makefile using git, make, and cmake. I think it could be worthwhile to look into using a C++ package manager, if possible.

Some options:
*[Ruslo](https://github.com/ruslo/hunter) - 900 stars. CMake-based cross-platform package manager. Has msgpack-c, Catch, openssl, Boost, Qt. Does NOT have sqlitecpp, as of now, but we could submit a request to add it.
*[Buckaroo](https://buckaroo.pm/) - 100 stars, but started this year. Has msgpack-c, Catch, and sqlitecpp.
*Create a custom package manager? It could be a simple package manager script (or a full-fledged program that we open-source! ... or not)

**Comment by Jldevictoria** [comment]
Going to pass on this for now, might reinvestigate if needed later.
