### ISSUE TITLE
Login Front-End Created

### ISSUE THREAD

**Issue by Jldevictoria** [Victory-Game-Studios/Oldentide#7]
The Login front-end system should include the graphical interface for the user to login with, the protocol that matches the back-end login server, and any hooks needed to implement it into the client.

**Comment by Jldevictoria** [comment]
GUI portion is complete!

**Comment by hintron** [comment]
What more needs to be done before this is considered complete?

**Comment by Jldevictoria** [comment]
About 80% complete. 

See See LoginManager.cs

**Comment by Jldevictoria** [comment]
To make this item completed, we need to have a method of storing the session id returned by the server after you successfully login through the client.  We also want the game server to be able to recognize this session id, and be able to use it to validate packets.

**Comment by Jldevictoria** [comment]
I'll try to finish this today If I have time.

**Comment by Jldevictoria** [comment]
Working!

The accountName and sessionId is stored in OldentidePlayerInformation.cs in the static variable.
